name: Code Testing

on:
  push:
    branches-ignore: ["main"]

jobs:
  cleanup_and_tests:
    runs-on: ubuntu-latest

    steps:
      - name: "print context info"
        run: |
          echo "github.event_name:" ${{github.event_name}}
          echo "github.event.action:" ${{github.event.action}}
          echo "github.actor:" ${{github.actor}}

      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: test with pytest
        run: |
          pytest

      - name: pre-commit auto-fix
        run: |
          pre-commit run --all-files
        continue-on-error: true

      - name: test with pre-commit
        run: |
          pre-commit run --all-files

      - name: commit report
        run: |
          git config --global user.name 'ðŸ¤– CI Tests'
          git config --global user.email 'ghost@users.noreply.github.com'
          git commit -am "ðŸ¤– Automated CI update"
          git push
        continue-on-error: true
